version: "3.9"

services:
  api:
    build: .
    command: uvicorn wallettaser.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////data/wallettaser.db
      WALLETTASER_DATA_ROOT: /data/reports
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - data:/data
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A wallettaser.celery_app.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: sqlite:////data/wallettaser.db
      WALLETTASER_DATA_ROOT: /data/reports
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  dashboard:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  data:
